AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PreprocessKvsRecording

  Sample SAM Template for PreprocessKvsRecording
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PreprocessKvsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PreprocessKvs/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          RECORDINGS_KEY_PREFIX: recordings/
          CLOUDFRONT_DOMAIN: https://d2i9chbrhts7m7.cloudfront.net

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PreprocessKvsFunction:
    Description: "Preprocess Kvs Lambda Function ARN"
    Value: !GetAtt PreprocessKvsFunction.Arn
  PreprocessKvsFunctionIamRole:
    Description: "Implicit IAM Role created for Preprocess Kvs function"
    Value: !GetAtt PreprocessKvsFunctionRole.Arn
